server:
  port: 8081
  
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: smtpTest.Ryu@gmail.com
    password: cmykdsjzcveskvpm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/PT_AM?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: root
    password:
  
  
mybatis:
  type-aliases-package: com.koreaIT.paintingTogether.vo
  
custom:
  siteName: paintingTogether
  siteMainUri: http://localhost:8081
  emailFrom: no-reply@localhost
  emailFromName: paintingTogether
  
  

  